
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: wishlist_dev
  template: template0

test:
  <<: *default
  database: wishlist_test
  template: template0

production:
  <<: *default
  database: wishlist_production
  username: wishlist
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
  
